name: build

on:
  push:
  pull_request:

jobs:
  zephyr-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install west

      - name: Init west workspace
        run: |
          west init -l .
          west update

      - name: Install ARM GNU toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Build nRF53 app
        env:
          ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
          GNUARMEMB_TOOLCHAIN_PATH: /usr
        run: |
          west build -b nrf5340dk/nrf5340/cpuapp app --sysbuild